
- name: Check if docker-compose.yml exists
  stat:
    path: /ptit-backend/flask-api/docker-compose.yml
  register: compose_file

- name: Run Docker Compose Down
  shell: sudo docker compose down
  args:
    chdir: /ptit-backend/flask-api
  when: compose_file.stat.exists
  
- name: Remove ptit-backend directory
  file:
    path: /ptit-backend                
    state: absent

- name: Create directory ptit-backend  
  file:
    path: /ptit-backend       
    state: directory
    mode: '0755'

- name: Copy flask-api directory
  copy:
    src: flask-api
    dest: /ptit-backend  

- name: Run Docker Compose Up
  shell: sudo docker compose up -d
  args:
    chdir: /ptit-backend/flask-api